server:
  port: 8085
spring:
  datasource:
# DB를 application.yamnl에서 통합(자동,1개만사용시)으로 관리할떄 사용
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://211.42.156.67:5432/nhjdb
#    username: nhjdba
#    password: 1234
# -------------------------------
# DB를 여러개를 사용해서 따로 수동으로 관리할때사용 (@Configration으로 java파일로 따로 관리해야함)
      hikari:
        jdbc-url: jdbc:postgresql://211.42.156.67:5432/nhjdb
        username: nhjdba
        password: 1234
        driver-class-name: org.postgresql.Driver
        maximum-pool-size: 20
        connection-timeout: 30000
#MyBatis 설정
#기존 mybatis-confgi.xml 에서 설정하던 옵션을 여기서 설정이 가능하다.
mybatis:
  # 기본경로는 src/main/resource를 path로 잡고 있기 때문
  # config를 파일로 관리할때 쓰는 방식
  config-location: classpath:config/Mybatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  # config를 통합적으로 관리할때 쓰는 방식
#  configuration:
#    map-underscore-to-camel-case: true
      